### ISSUE TITLE
[Feautre Request] Filled folder icons

### ISSUE THREAD

**Issue by ajitid** [rastikerdar/vscode-seedling-icon-theme#1]
Folder icons like Monokai Pro which are filled rounded chevrons instead.  

![seedling](https://user-images.githubusercontent.com/26769888/51909007-73e52b80-23f1-11e9-8b90-f6e313f3e0ae.png)

Filled chevrons also go with VS Code own's chevron (see chevron at top left of the picture)

**Comment by ajitid** [comment]
Yes

**Comment by ajitid** [comment]
Is filling configurable too?

**Comment by rastikerdar** [comment]
Updated in v0.2.0 
[vscode-seedling-icon-theme](https://marketplace.visualstudio.com/items?itemName=rastikerdar.vscode-seedling-icon-theme)
