### ISSUE TITLE
Julia Icon missing

### ISSUE THREAD

**Issue by musm** [rastikerdar/vscode-seedling-icon-theme#2]
Love this icon theme (best I've used). Just one tiny problem, no Julia icon.

Here's the repo with the official graphics that could be used: https://github.com/JuliaLang/julia-logo-graphics

**Comment by rastikerdar** [comment]
Thanks for this issue and the link. Added in version `0.7.0`.
![Screenshot at 2020-10-27 08-07-28](https://user-images.githubusercontent.com/3116038/97257785-31ea5300-182c-11eb-816b-cf3892628ffe.png)

**Comment by musm** [comment]
thank you!
