### ISSUE TITLE
Handlebars icon missing

### ISSUE THREAD

**Issue by TorSalveRH** [rastikerdar/vscode-seedling-icon-theme#3]
Hey there, great theme you have built! :)

Unfortunately, icons for *.hbs and *.handlebars-files are missing ([https://handlebarsjs.com/](https://handlebarsjs.com/)). I would imagine an icon similar to their [favicon](https://handlebarsjs.com/images/favicon.png).

**Comment by rastikerdar** [comment]
Thank you for this issue. Added in version 0.9.0.
