### ISSUE TITLE
Golang file icon theme

### ISSUE THREAD

**Issue by blessedmadukoma** [rastikerdar/vscode-seedling-icon-theme#4]
Please, could you use the golang mascot for the file icon theme? Not the letter G. Thank you

**Comment by rastikerdar** [comment]
Thanks for this issue. Added in version 0.8.0.
![Screenshot at 2021-02-25 20-49-13](https://user-images.githubusercontent.com/3116038/109190989-eed4c800-77aa-11eb-9fa4-feafe4a62490.png)
