### ISSUE TITLE
Jupyter notebook icon

### ISSUE THREAD

**Issue by musm** [rastikerdar/vscode-seedling-icon-theme#5]
Would love to see icons for jupyter notebooks `.ipynb` added, e.g. something like a notebook icon.

**Comment by musm** [comment]
bump :smil

**Comment by rastikerdar** [comment]
Is this icon (and color) suitable for `jupyter|.ipynb` files?
![Screenshot at 2022-03-18 22-45-26](https://user-images.githubusercontent.com/3116038/159069708-746c7527-9993-4332-90ac-16402e954765.png)

**Comment by musm** [comment]
I feel like that's difficult to read? Perhaps a notebook style icon like:
![Uploading image.png…]()

**Comment by rastikerdar** [comment]
I took it from the official logo:
![Screenshot at 2022-03-19 14-21-03](https://user-images.githubusercontent.com/3116038/159118059-15f95059-ff05-481e-935f-a4e4d904e701.png)

How is this? If OK then orange or blue?

![Screenshot at 2022-03-19 14-22-20](https://user-images.githubusercontent.com/3116038/159118151-ebfcc41e-b7cb-4565-bc97-f6269c8be259.png)
![Screenshot at 2022-03-19 14-22-49](https://user-images.githubusercontent.com/3116038/159118156-541323c5-3118-4d04-aecf-275223170d4a.png)

Orange is taken from the official logo

**Comment by musm** [comment]
orange color looks beautiful

**Comment by rastikerdar** [comment]
Thanks, added in version 0.10.0
