### ISSUE TITLE
Yaml  file icon missing

### ISSUE THREAD

**Issue by Angel-Mu** [rastikerdar/vscode-seedling-icon-theme#6]
Would be awesome to have `yaml` | `yml` icon instead of an exclamation mark, for those who are into serverless and configuration as code :)
### Current
![image](https://user-images.githubusercontent.com/6799039/147115930-8e3312b6-5e4d-40e0-a63f-6136811e11fa.png)

**Comment by atjbramley** [comment]
Upvote for this feature request!

**Comment by rastikerdar** [comment]
Sorry guys, what icon should I use for `.yaml`?
This is from `seti icon pack`:
![Screenshot at 2022-03-18 22-50-17](https://user-images.githubusercontent.com/3116038/159070477-f5a9c91e-e5ae-4613-943f-543aa730a46f.png)

This the official icon:
![Screenshot at 2022-03-18 22-53-41](https://user-images.githubusercontent.com/3116038/159070772-c2212e2d-65f4-4bba-bbe2-5eba025bbaea.png)

Or just use the letters "yml"

**Comment by musm** [comment]
Monakai Pro uses:
<img width="69" alt="image" src="https://user-images.githubusercontent.com/4319522/159131402-f65cee5d-04d6-43ae-99d8-62a828452252.png">

Another Icon package:
<img width="61" alt="image" src="https://user-images.githubusercontent.com/4319522/159131448-ab66a9c9-42de-4ba3-8a08-8ef962c57576.png">


It would be great if you could also add `.toml` icon at the same time!

**Comment by Angel-Mu** [comment]
Using just the letters `yml` or the one @musm mentioned from monokai pro

**Comment by rastikerdar** [comment]
Hope you like this 
![Screenshot at 2022-03-19 23-25-40](https://user-images.githubusercontent.com/3116038/159136470-9ee024cc-b0b3-48a6-91c2-868932709cc8.png)

**Comment by musm** [comment]
Looks good! Any chance for a `.toml`  ?

**Comment by Angel-Mu** [comment]
> Hope you like this 
> 
> ![Screenshot at 2022-03-19 23-25-40](https://user-images.githubusercontent.com/3116038/159136470-9ee024cc-b0b3-48a6-91c2-868932709cc8.png)
> 
> 

Looks great! 🎉 thanks for jumping into this!

**Comment by rastikerdar** [comment]
Thanks, added in version 0.10.0
