### ISSUE TITLE
JenkinsFile icon missing

### ISSUE THREAD

**Issue by atjbramley** [rastikerdar/vscode-seedling-icon-theme#7]
Hello!

Love your icon theme. 

Please could we get a Jenkinsfile icon for those of us who work with CICD pathways?

Thanks!

**Comment by rastikerdar** [comment]
Thanks, added in version 0.10.0

**Comment by atjbramley** [comment]
Sorry, should have responded ages ago.  Love the icons you included in 0.10.0 - great job :)
