### ISSUE TITLE
Markdown icon

### ISSUE THREAD

**Issue by LucasCtrl** [rastikerdar/vscode-seedling-icon-theme#8]
Hey 👋

I really like you icon theme!
Is it possible to have a markdown icon (`.md` files)

Cheers !

**Comment by rastikerdar** [comment]
How is this?
![Screenshot at 2022-03-19 00-22-40](https://user-images.githubusercontent.com/3116038/159081647-5983000b-168b-440f-b50d-51836c4e3f7f.png)

**Comment by musm** [comment]
Looks good, what does the downward pointing arrow mean?

**Comment by rastikerdar** [comment]
:mark: :down:

Main logo:
![Screenshot at 2022-03-19 21-48-02](https://user-images.githubusercontent.com/3116038/159133622-a574ce26-32e5-4937-a1e7-07ef45f07946.png)

**Comment by rastikerdar** [comment]
Thanks, added in version 0.10.0

**Comment by LucasCtrl** [comment]
My lord, thanks 😙
