### ISSUE TITLE
LaTeX icon missing 

### ISSUE THREAD

**Issue by musm** [rastikerdar/vscode-seedling-icon-theme#9]

**Comment by rastikerdar** [comment]
Which icon do you recommend? The bird from official logo or letters `tex`?
![Screenshot at 2022-03-19 00-17-30](https://user-images.githubusercontent.com/3116038/159081067-f9663ce3-227a-4277-ba80-56e767ceb79c.png)

**Comment by musm** [comment]
That's pretty nice!

**Comment by musm** [comment]
<img width="69" alt="image" src="https://user-images.githubusercontent.com/4319522/159131468-a5fbe5d3-9db9-4b50-906e-083bae44a538.png">

I did some exploring. It looks like many use the `TeX` letters, but honestly the bird is very cute so I'm deferring to your expertise on which would work better.

**Comment by rastikerdar** [comment]
Thanks, added in version 0.10.0
